### PR TITLE
fix: Remove upper-bound version constraint from SCI

### PR DESCRIPTION
**Pull request by austindrenski**
Fixes: #170

See: #136, #137, #170 

___

_Anticipate similar arguments/discussion as in #137, but opening as a companion to #170 because this is causing me real-world grief today 🙃_

### CODE REVIEW

**Comment by beeme1mr** [comment]
No idea why the code coverage report is failing...

At any rate, I'll add the people from the referenced thread.

**Review by benjiro — APPROVED** [review]

**Comment by toddbaert** [comment]
@kinyoklion Has you opinion on this changed at all since #170 ?

**Comment by austindrenski** [comment]
Bumping because this is unfortunately causing an increasing amount of developer friction inside my org.

Including this package breaks our in-house source generators when invoked by IDE-triggered design-time builds in such a way that my normally strong msbuild-foo has thus far been unable to combat.

I would like to get some movement on this today, otherwise I'm looking at needing to publish a forked package to appease a growing horde of angered devs. _(This is, of course, a me problem, so I don't mention it to force a decision one way or the other, just to say that it would be nice to hear from folks on whether this is a quick action or something I need to self-serve for the foreseeable future.)_

/cc @toddbaert @kinyoklion

**Comment by toddbaert** [comment]
> Can someone catch me up on why we're going out of our way to set upper-bound constraints in the first place?
> 
> Originally, I assumed it was something specific about `System.Collections.Immutable` that we were depending on (e.g. internal impl details, sketchy reflection, etc.), but now noticing that we do this in a bunch of places, so wondering if this is just an artifact of someone's repo template, or if there's some bigger concern that I'm missing 🤔

I think it was just out of fear of breaking changes in further releases of these dependencies, but I think I'm on board with just removing the upper bounds.

**Review by toddbaert — APPROVED** [review]

**Comment by toddbaert** [comment]
@austindrenski I've removed the upper bound on `System.Threading.Channels` as well.

**Pull request merged**
