### PR TITLE
fix: max System.Collections.Immutable version ++

### PR DESCRIPTION
**Pull request by toddbaert**
remove max System.Collections.Immutable version

fixes: https://github.com/open-feature/dotnet-sdk/issues/136

### CODE REVIEW

**Review by benjiro — APPROVED** [review]

**Comment by kinyoklion** [comment]
Generally speaking this is a little concerning, because MS could change something and cause unpredictable behavior. On the other hand they have given up on the version having much meaning, so maybe this is the only alternative.

**Comment by toddbaert** [comment]
> Generally speaking this is a little concerning, because MS could change something and cause unpredictable behavior. On the other hand they have given up on the version having much meaning, so maybe this is the only alternative.

I was concerned about this too... but I think if there was a breaking change the impacted us, we would see it relatively quickly in the CI, as long is it [was in .NET 6 or 7.](https://github.com/open-feature/dotnet-sdk/blob/main/.github/workflows/ci.yml#L24-L26). Maybe I'm wrong about that.

**Comment by kinyoklion** [comment]
> > Generally speaking this is a little concerning, because MS could change something and cause unpredictable behavior. On the other hand they have given up on the version having much meaning, so maybe this is the only alternative.
> 
> I was concerned about this too... but I think if there was a breaking change the impacted us, we would see it relatively quickly in the CI, as long is it [was in .NET 6 or 7.](https://github.com/open-feature/dotnet-sdk/blob/main/.github/workflows/ci.yml?rgh-link-date=2023-07-14T18%3A16%3A28Z#L24-L26). Maybe I'm wrong about that.

I am sure we would detect it fast, but would consumer applications basically be breaking at the same time? Because they nuget install and different packages are fetched?

**Comment by kinyoklion** [comment]
Generally speaking dotnet tries to install the lowest compatible version (backward from most package systems), at least it used to, so it may not be a problem.

**Comment by toddbaert** [comment]
> Generally speaking dotnet tries to install the lowest compatible version (backward from most package systems), at least it used to, so it may not be a problem.

I just found this out, yes. Locally this is causing `1.7.1` to be resolved, which doesn't really help in testing.

I just manually forced version 7 and run the unit and e2e test suite and that worked... so I guess the more conservative option would be to allow up to v8.

Any thoughts?

**Comment by toddbaert** [comment]
> Generally speaking a dotnet application will actually automatically generate binding redirects allowing you to use any version. ASP.Net applications do not, which is generally where this problem comes up.
> 
> For instance, for LD, this comes up with Microsoft.Logging.Extensions all the time:
> 
> ```
> <dependentAssembly>
>   <assemblyIdentity name="Microsoft.Extensions.Logging"
>     publicKeyToken="adb9793829ddae60"
>     culture="en-us" />
>   <bindingRedirect oldVersion="6.0.0" newVersion="7.0.0.0" />
> </dependentAssembly>
> ```
> 
> Updating it to 8.0.0 is safest. But it does mean it needs basically annually updated. Because MS will release the next one.

OK I'll do the conservative thing for now and then think on it more. Maybe we can automate it somehow.

**Review by kinyoklion — APPROVED** [review]

**Comment by kinyoklion** [comment]
May want to update the PR title, for the release note.

**Pull request merged**
