### PR TITLE
feat: Feature Provider Enhancement - #321

### PR DESCRIPTION
**Pull request by arttonoyan**
This update focuses on enhancing the feature provider integration and testing framework, incorporating improvements to flexibility, usability, and testing capabilities.
This update addresses [GitHub Issue #321](https://github.com/open-feature/dotnet-sdk/issues/321) in the OpenFeature .NET SDK repository.

---

### Key Enhancements

1. **Dependency Injection (DI) Enhancements:**
   - Improved lifecycle management for better resource handling.
   - Streamlined registration for feature providers, reducing configuration complexity.
   - Introduced the `AddProvider` extension method to simplify and adapt feature provider integration during service setup.

2. **Simplified Codebase:**
   - Removed `FeatureProviderFactory` logic, eliminating unnecessary complexity and improving usability.

3. **Improved InMemoryProvider:**
   - Enhanced the registration process for the `InMemoryProvider`, enabling smoother and more intuitive usage.

4. **Testing Improvements:**
   - Established a dedicated integration test project for comprehensive validation.
   - Improved overall test coverage, ensuring the reliability and robustness of the framework.

---

#### Service Registration
```csharp
builder.Services.TryAddSingleton<IFeatureFlagConfigurationService, FlagConfigurationService>();

builder.Services.AddHttpContextAccessor();
builder.Services.AddOpenFeature(cfg =>
{
    cfg.AddHostedFeatureLifecycle();
    cfg.AddContext((builder, provider) =>
    {
        // Retrieve the HttpContext from IHttpContextAccessor, ensuring it's not null.
        var context = provider.GetRequiredService<IHttpContextAccessor>().HttpContext
            ?? throw new InvalidOperationException("HttpContext is not available.");

        var userId = UserInfoHelper.GetUserId(context);
        builder.Set("user", userId);
    });
    cfg.AddInMemoryProvider(provider =>
    {
        var flagService = provider.GetRequiredService<IFeatureFlagConfigurationService>();
        return flagService.GetFlags();
    });
});
```

#### FlagConfigurationService Implementation
```csharp
public class FlagConfigurationService : IFeatureFlagConfigurationService
{
    private readonly IDictionary<string, Flag> _flags;

    public FlagConfigurationService()
    {
        _flags = new Dictionary<string, Flag>
        {
            {
                "feature-a", new Flag<bool>(
                    variants: new Dictionary<string, bool>
                    {
                        { "on", true },
                        { "off", false }
                    },
                    defaultVariant: "on", context => {
                        var id = context.GetValue("user").AsString;
                        if (id == null)
                        {
                            return "on"; // Default variant
                        }

                        return id == TestUserId ? "off" : "on";
                    })
            }
        };
    }

    public Dictionary<string, Flag> GetFlags() => _flags.ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
}
```

### CODE REVIEW

**Comment by arttonoyan** [comment]
@toddbaert @askpt @beeme1mr Hi guys, I hope you are doing well! 🖐
I recently submitted this PR that addresses the https://github.com/open-feature/dotnet-sdk/issues/321 issue. It's been a few days, and I wanted to kindly request that someone take a look when they have a moment.
Your feedback is greatly appreciated.
Thanks!

**Review by askpt — APPROVED** [review]
LGTM! It seems that some of the DI extension classes are missing coverage. I wonder if it is worth excluding them from code coverage for the build to pass.

**Review by beeme1mr — APPROVED** [review]
Hey @arttonoyan, sorry for the delay. Last week was a holiday in the US.

The change looks good to me. Should the examples in the readme also be updated?

**Comment by arttonoyan** [comment]
> Hey @arttonoyan, sorry for the delay. Last week was a holiday in the US.
> 
> The change looks good to me. Should the examples in the readme also be updated?

Oh, no problem! I forgot about that. 😊 Yes, of course, I’ll update the documentation as well. I just wanted to get your feedback first, and I’ll make sure to update it before merging.

**Comment by toddbaert** [comment]
@ghelyar does this solve the issues you mentioned?

**Comment by ghelyar** [comment]
yes

**Review by toddbaert — CHANGES_REQUESTED** [review]
This looks good to me and addresses the outside feedback.

My only blocker is updated documentation. Once you have that I can squash down the commits to one for you to sign off on if you want, @arttonoyan .

**Comment by arttonoyan** [comment]
> This looks good to me and addresses the outside feedback.
> 
> My only blocker is updated documentation. Once you have that I can squash down the commits to one for you to sign off on if you want, @arttonoyan .

Thanks, @toddbaert ! I’ve updated the document, and I think this version is much more flexible - I’m really happy with how it’s shaping up. It’s great to see external feedback coming in; it’s been super helpful. 
For this release, I also added integration tests, which made spotting issues so much easier. I’m sure we’ll keep improving it even more in the future!
cc: @beeme1mr @askpt @ghelyar

**Comment by beeme1mr** [comment]
Hey @toddbaert, it looks like this PR is ready! Could you please take a look when you have a moment?

**Comment by arttonoyan** [comment]
> Hey @toddbaert, it looks like this PR is ready! Could you please take a look when you have a moment?

Hey @toddbaert, just a friendly reminder to take a look when you have a moment. 😊

**Pull request merged**
