### PR TITLE
feat!: add cancellation tokens

### PR DESCRIPTION
**Pull request by austindrenski**
See: https://github.com/open-feature/dotnet-sdk/pull/154#issuecomment-1894703244

### CODE REVIEW

**Review by benjiro — APPROVED** [review]
I'm fine with this, probably my bad for missing putting the CTs in the first place. Thanks for fixing it up, makes sense to support this specially if the library is being consumed in a web app.

Async suffix is a well understood convention and mentioned many times in the originally docs. I'm good with adding it, breaking change is minimal.

Nice work

**Review by toddbaert — CHANGES_REQUESTED** [review]
I definitely want to do this, but I want to collect a few breaking changes and create an issue for them all... then we can perhaps maintain a v2 branch for a while, and merge it all at once when we're ready to release.

I'll create that issue to discuss, but blocking for now. Let me know if you disagree.

**Comment by kinyoklion** [comment]
We should maybe update the conventional commit tag to have an exclamation point. Makes it easy to see that it needs to be held off.

**Comment by toddbaert** [comment]
I'm assigning this to myself. Next week I'll work on cleaning it up, which will hopefully also help me understand how we can best use these tokens in terms of how they integrate with the rest of the SDK's semantics.

> We should maybe update the conventional commit tag to have an exclamation point. Makes it easy to see that it needs to be held off.

Did this, thanks @kinyoklion

**Comment by toddbaert** [comment]
I've started on this and https://github.com/open-feature/dotnet-sdk/pull/185

**Comment by toddbaert** [comment]
Closing and continuing with https://github.com/open-feature/dotnet-sdk/pull/268

**Pull request closed without merging**
